### ISSUE TITLE
`go get -u github.com/jeanlaurent/stupid` broken

### ISSUE THREAD

**Issue by guillaumerose** [jeanlaurent/stupid#16]
The binary is not created, usage is now:

`go get -u github.com/jeanlaurent/stupid/cmd/stupid`

**Comment by mat007** [comment]
It's a bit sad that this is now much longer to type. Also the pun is not as funny…
@vdemeester do you have an opinion?

**Comment by vdemeester** [comment]
That said, we should not go get it (for several reasons).

I can do 2 things : a main.go on root (to allow the go get, and/or update the README)

**Comment by mat007** [comment]
Readme updated!
