### ISSUE TITLE
Add badge to CircleCI at the top of the readme

### ISSUE THREAD

**Issue by mat007** [jeanlaurent/stupid#7]
@jeanlaurent I don't have the credentials to manage the tokens or whatever is required to generate a link to the CircleCI badge, so put a naked link at the top of the README.md for the time being.

**Comment by jeanlaurent** [comment]
done in a35e91833fa938e9d8c31fa5653745a8e2aa457c

**Comment by jeanlaurent** [comment]
invited you as Github collaborator on the project

**Comment by mat007** [comment]
Oh right, for some reason I thought this needed a token on CircleCI…
Thanks!
